site_name: drf-serialization-magic
site_description: Serialization magic helps you boost your code and reduce duplication in your DRF project when working with Serializers

repo_url: https://github.com/tkppro/drf-serialization-magic

site_dir: html
theme: readthedocs
extra_css:
  - css/index.css
nav:
  - Home: 'index.md'
  - Overview: 'overview.md'
  - Installation: 'installation.md'
  - User Guide:
    - Views: 'usage-views.md'
    - 'API Reference': 'usage-api.md'
  - Examples: 'examples.md'
  - Contributing: 'contributing.md'
